apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo  

spec:
  replicas: 3

  selector:
    matchLabels:
       app: devops-demo 
    
  template:
       metadata:
         labels:
           app: devops-demo 
    
       spec:
         containers:
            - name: devops-demo 
              image: ghcr.io/ss1984-roblox/devops-demo:3d6f92502d72d984276a121be0c1472730eb5e66


              imagePullPolicy: Always

              ports:
              - containerPort: 5000
          
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"

                limits:
                  cpu: "500m"
                  memory: "256Mi"
              